//PROFILE
export const SET_USER_PROFILE = 'SET_USER_PROFILE';

//PROFILE -- posts
export const ADD_POST = 'ADD_POST';
export const UPDATE_NEW_POST_TEXT = 'UPDATE_NEW_POST_TEXT';

//DIALOGS
export const UPDATE_NEW_MESSAGE_TEXT = 'UPDATE_NEW_MESSAGE_TEXT';
export const SEND_MESSAGE = 'SEND_MESSAGE';

//FIND_FRIENDS
export const SET_USERS = 'SET_USERS';
export const TOGGLE_FRIEND = 'TOGGLE_FRIEND';
export const TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING';
export const TOGGLE_IS_ADDING_FRIEND = 'TOGGLE_IS_ADDING_FRIEND';
export const TOGGLE_WHICH_FRIEND_IS_ADDING = 'TOGGLE_WHICH_FRIEND_IS_ADDING';

//FIND_FRIENDS -- pagination
export const SET_USERS_COUNT = 'SET_USERS_COUNT';
export const SET_TOTAL_COUNT = 'SET_TOTAL_COUNT';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';

//AUTH
export const SET_ME = 'SET_USER_DATA';
export const SET_AUTH_USER_PROFILE = 'SET_AUTH_USER_PROFILE';
export const TOGGLE_AUTH = 'TOGGLE_AUTH';
export const TOGGLE_IS_AUTH_DATA_INCORRECT = 'TOGGLE_IS_AUTH_DATA_INCORRECT';
export const TOGGLE_IS_AUTHORIZING = 'TOGGLE_IS_AUTHORIZING';

//APP
export const TOGGLE_INITIALIZED = 'TOGGLE_INITIALIZED';